---

# - name: filebeat | Install
#   package: name=filebeat state=present
#   register: install_filebeat

- name: filebeat | Load Filebeat.yml
  template:
      src: "filebeat.yml.j2"
      dest: "/etc/filebeat/filebeat.yml"
      owner: root
      group: root
      mode: 0700

- name: filebeat | Enable Service
  service:
    name: filebeat
    state: started
    enabled: yes
