---
# tasks file for building consul-server

- name: Setup the Consul Server Configuration
  template:
      src: "server.json.j2"
      dest: "/etc/consul.d/server.json"
      owner: root
      group: root
      mode: 0777
  when: "'masters' in group_names"
  notify: Start the consul service
