---
# tasks file for building consul-server

- name: Setup the Consul Server Configuration
  template:
      src: "server.json.j2"
      dest: "/etc/consul.d/server.json"
      owner: root
      group: root
      mode: 0777

- name: Copy the Consul Setup Script onto the server
  template:
      src: "setup-consul-server.sh.j2"
      dest: "/opt/consul/setup-consul-server.sh"
      owner: root
      group: root
      mode: 0777

# TODO: Allow Ansible to manage this task
- name: Start Consul 
  shell: sudo service consul start
  args:
    chdir: "/opt/consul"
    creates: consul-server-configured.done
