---
# handlers file for elasticsearch-client

- name: Restart ES service
  service:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: Start ES Head service
  service:
    name: eshead
    state: restarted
    enabled: yes
  become: yes
