# Infrastructure
dc: "usa"
env: dev #Specify Environment as required. "prod" "sit" "uat" etc...

# Networking
host_ip: "{{ ansible_all_ipv4_addresses[0]}}"
client_ip: "{{ ansible_all_ipv4_addresses[1]}}"
# Consul
consul_config_dir: /etc/consul.d
consul_opt_dir: /opt/consul
consul_data_dir: /opt/consul/data

# Elasticsearch
es_host: "{{ client_ip }}"
es_url: "http://{{ client_ip }}:9200"
es_cluster_name: "usa-{{ env }}"
es_data_dir: /data/elasticsearch
es_head_dir: /opt/elasticsearch/elasticsearch-head
es_minimum_master_nodes: 2
es_gateway_recover_after_nodes: 5 # total number of nodes - 1. Including the client nodes)
es_gateway_expected_nodes: 6 # How many nodes should be in the cluster in total
es_gateway_recover_after_time: 5m # How long should the cluster wait for all nodes to start up
# node_version: 6.14.3

# Kibana
kibana_version: "5.4"
kib_dir: /opt/kibana
kib_config_dir: "{{ kib_dir }}/config"
# kibana_server_port: 5601


#Logstash
ls_host: 10.10.10.11
ls_conf_dir: /etc/logstash/conf.d
ls_tls_dir: /etc/pki/tls
ls_cert_dir: "{{ ls_tls_dir }}/certs"
ls_pk_dir: "{{ ls_tls_dir }}/private"
