---
# tasks file for building consul-server
- name: Create common directories across the infrastructure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items:
    - "/etc/consul.d"
    - "/opt/consul"
    - "/opt/consul/data"


- name: Setup systemd service for consul
  template:
      src: "systemd_consul.conf.j2"
      dest: "/etc/systemd/system/consul.service"
      owner: root
      group: root
      mode: 0700

- name: Setup the Common json configurations
  template:
      src: "common.json.j2"
      dest: "/etc/consul.d/common.json"
      owner: root
      group: root
      mode: 0775
  notify: Start the consul service
