---
# tasks file for building consul-server
- name: Create common directories across the infrastructure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - "/etc/consul.d"
    - "/opt/consul"
    - "/opt/consul/data"

# TODO: use systemd instead of init
- name: Setup the Upstart Job
  template:
      src: "upstart_consul.conf.j2"
      dest: "/etc/init/upstart_consul.conf"
      owner: root
      group: root
      mode: 0700

- name: Setup the Common json configurations
  template:
      src: "common.json.j2"
      dest: "/etc/consul.d/common.json"
      owner: root
      group: root
      mode: 0775
     

