- name: Create directories for Elasticsearch
  file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0774
  with_items:
    - "{{ es_data_dir }}"

- name: Deploy Elastic search configuration on respective nodes
  template:
      src: "elasticsearch.yml.j2"
      dest: "/etc/elasticsearch/elasticsearch.yml"
      owner: elasticsearch
      group: elasticsearch
      mode: 0660
  notify: Restart ES service # This should be removed when we introduce Consul Templates


- name: Enable and Start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
