- name: Create directories for Elasticsearch
  file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0774
  with_items:
    - "{{ es_data_dir }}"

- name: ELK Stack| Add Elasticsearch apt key.
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present
  register: elk_apt_key

# - name: Kibana | Add repository.
#   apt_repository:
#     repo: 'd https://artifacts.elastic.co/packages/5.4/apt stable main'
#     state: present
#     update_cache: yes

- name: ELK Stack | repository
  shell: echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
  when: elk_apt_key.changed

- name: Deploy Elastic search configuration on respective nodes
  template:
      src: "elasticsearch.yml.j2"
      dest: "/etc/elasticsearch/elasticsearch.yml"
      owner: elasticsearch
      group: elasticsearch
      mode: 0660
  notify: Restart ES service # This should be removed when we introduce Consul Templates


- name: Enable and Start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
